CREATE TABLE SON_USERS(
    USER_ID NUMBER,
    USER_NAME VARCHAR2(255 CHAR),
    USER_PASSWORD VARCHAR2(255 CHAR),
    CONSTRAINT PK_SON_USER PRIMARY KEY (USER_ID)
);

CREATE TABLE SON_CATEGORY (
    CATEGORY_ID NUMBER,
    CATEGORY_NAME VARCHAR2(255 CHAR),
    CONSTRAINT PK_SON_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE SON_NEWS (
    NEWS_ID NUMBER,
    NEWS_TITLE VARCHAR2(255 CHAR),
    CONTENT CLOB,
    PHOTO_THUMBNAIL VARCHAR2(255 CHAR),
    VIEW_COUNT NUMBER DEFAULT 0,
    PUBLISH_DATE TIMESTAMP,
    CATEGORY_ID NUMBER,
    CONSTRAINT PK_SON_NEWS PRIMARY KEY (NEWS_ID),
    CONSTRAINT FK_NEWS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SON_CATEGORY(CATEGORY_ID)
);